-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2016-05-18 11:53:56 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE Diagnoza
  (
    ID_pacjenta          INTEGER NOT NULL ,
    ID_diagnozy          INTEGER ,
    Diagnoza             VARCHAR2 (30) ,
    Pacjenci_ID_pacjenta INTEGER NOT NULL
  )
  LOGGING ;
ALTER TABLE Diagnoza ADD CONSTRAINT Diagnoza_PK PRIMARY KEY ( ID_pacjenta, Pacjenci_ID_pacjenta ) ;


CREATE TABLE Leki
  (
    ID_pacjenta          INTEGER NOT NULL ,
    ID_leku              INTEGER ,
    Nazwa_leku           VARCHAR2 (30) ,
    Pacjenci_ID_pacjenta INTEGER NOT NULL
  )
  LOGGING ;
ALTER TABLE Leki ADD CONSTRAINT Leki_PK PRIMARY KEY ( ID_pacjenta, Pacjenci_ID_pacjenta ) ;


CREATE TABLE Pacjenci
  (
    ID_pacjenta    INTEGER NOT NULL ,
    Imie           VARCHAR2 (30) ,
    Nazwisko       VARCHAR2 (30) ,
    INFO           VARCHAR2 (30) ,
    Data_urodzenia DATE
  )
  LOGGING ;
ALTER TABLE Pacjenci ADD CONSTRAINT Pacjenci_PK PRIMARY KEY ( ID_pacjenta ) ;


CREATE TABLE Wizyty
  (
    ID_wizyty            INTEGER NOT NULL ,
    ID_pacjenta          INTEGER ,
    Komentarz            VARCHAR2 (30) ,
    Data_wizyty          DATE ,
    Pacjenci_ID_pacjenta INTEGER NOT NULL
  )
  LOGGING ;
ALTER TABLE Wizyty ADD CONSTRAINT Wizyty_PK PRIMARY KEY ( ID_wizyty, Pacjenci_ID_pacjenta ) ;


ALTER TABLE Diagnoza ADD CONSTRAINT Diagnoza_Pacjenci_FK FOREIGN KEY ( Pacjenci_ID_pacjenta ) REFERENCES Pacjenci ( ID_pacjenta ) NOT DEFERRABLE ;

ALTER TABLE Leki ADD CONSTRAINT Leki_Pacjenci_FK FOREIGN KEY ( Pacjenci_ID_pacjenta ) REFERENCES Pacjenci ( ID_pacjenta ) NOT DEFERRABLE ;

ALTER TABLE Wizyty ADD CONSTRAINT Wizyty_Pacjenci_FK FOREIGN KEY ( Pacjenci_ID_pacjenta ) REFERENCES Pacjenci ( ID_pacjenta ) NOT DEFERRABLE ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0











